### ISSUE TITLE
领域层的代码概念很赞，只是没有看到 factory 的概念，关于值对象我有点疑问

### ISSUE THREAD

**Issue by junmaqiang** [jettjia/go-ddd#20]
##下面是关于工厂的
或许项目小的时候不用考虑工厂的概念；
不过按照DDD的描述来设计项目的话，工厂的实现也是有必要的；
我之前有看到人家把工厂写在应用层的，也有看到把工厂写到聚合内的；

##下面是关于值对象的
值对象，按照DDD的描述应该放在领域内，而且保持小写，外面不可以访问，但是这里有个问题，我发现你代码里面的应用层下 assembler 和 dto 都要用到各种实体和值对象，这样的话，领域内的实体和值对象不就暴露了嘛?
我也有看到人家把值对象和实体写到基础设施层下面，作为共用的；

总体看下来，这个仓库的代码 有不少地方都可以参考和学习的，为作者点赞。

**Comment by jettjia** [comment]
> ##下面是关于工厂的 或许项目小的时候不用考虑工厂的概念； 不过按照DDD的描述来设计项目的话，工厂的实现也是有必要的； 我之前有看到人家把工厂写在应用层的，也有看到把工厂写到聚合内的；
> 
> ##下面是关于值对象的 值对象，按照DDD的描述应该放在领域内，而且保持小写，外面不可以访问，但是这里有个问题，我发现你代码里面的应用层下 assembler 和 dto 都要用到各种实体和值对象，这样的话，领域内的实体和值对象不就暴露了嘛? 我也有看到人家把值对象和实体写到基础设施层下面，作为共用的；
> 
> 总体看下来，这个仓库的代码 有不少地方都可以参考和学习的，为作者点赞。

关于factory和值对象部分，当初设计的时候就去掉了。一些较复杂的部分，都没设计到里面。
当然，也欢迎你补充这部分的。

**Comment by junmaqiang** [comment]
目前还不具备补充能力，待我掌握了DDD，我想我可以的。。。
